name = input("Enter your name: ")
age = int(input("Enter your age: "))
dept = input("Enter your department: ")
clg_name = input("Enter your college name: ")
year = int(input("Enter your year: "))
city = input("Enter your city: ")
print("------------------STUDENT DETAILS-----------------")
print("Name          :",name)
print("Age           :",age)
print("Department    :",dept)
print("College Name  :",clg_name)
print("Year          :",year)
print("City          :",city)