text = str(input("Enter the string:")) 
print("Original: ", text) 
print("Uppercase: ", text.upper()) 
print("Lowercase: ", text.lower()) 
print("Title case: ", text.title()) 
print("Count of 'a': ", text.count('a')) 
print("Count of 'e': ", text.count('e')) 
print("Starts with 'The': ", text.startswith("The")) 
print("Ends with '.': ", text.endswith("."))